apiVersion: v1
kind: Service
metadata:
  name: todo-client-service
spec:
  selector:
    app: todo-client-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31101
  type: LoadBalancer
  loadBalancerIP: 10.10.10.10