apiVersion: v1
kind: Service
metadata:
  name: todo-app-frontend
  labels:
    app/tier: frontend 
    app/release: experimental
    app/project: demo
    app/environment: development
  namespace: demo
spec:
  selector:
    app/tier: frontend 
    app/release: experimental
    app/project: demo
    app/environment: development
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31101
