apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-client-app
  template:
    metadata:
      labels:
        app: todo-client-app
    spec:
      containers:
        - image: ghcr.io/astridstar/todo-client-kubernetes-app:latest
          name: container1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson-github-com
