apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-frontend
  labels:
    app/tier: frontend 
    app/release: experimental
    app/project: demo
    app/environment: development
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app/tier: frontend 
      app/release: experimental
      app/project: demo
      app/environment: development
  template:
    metadata:
      labels:
        app/tier: frontend 
        app/release: experimental
        app/project: demo
        app/environment: development
    spec:
      containers:
        - image: ghcr.io/astridstar/todo-app-frontend:latest
          name: todo-app-frontend
#          imagePullPolicy: Never
