name: Build and deploy demo web server

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  REGISTRY: ghcr.io # Using Github container repository
  REPOSITORY: ghcr.io/astridstar/demo-to-app/
  SERVER_IMAGE_TAG: ghcr.io/astridstar/demo-to-app/backend

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #      - name: Build the server Docker mage
      #        working-directory: ./server
      #       run: docker build . --file Dockerfile --tag ${{ env.SERVER_IMAGE_TAG }}

      - name: Convert repository name to lowercase
        run: |
          echo ${ENV_REPOSTR=$( echo "${{ github.repository }}" | tr "[:upper:]" "[:lower:]")}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ env.SERVER_IMAGE_TAG }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: ${{ env.SERVER_IMAGE_TAG }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: 'github_token=${{ secrets.GITHUB_TOKEN }}'

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  scan:
    needs: build
    name: Trivy Scan
    runs-on: ubuntu-latest

    steps:
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.SERVER_IMAGE_TAG }}:${{ github.sha }}'
          format: 'table'
          #exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
          scan-type: 'image'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'trivy-results.sarif'
